### PR TITLE
Update travis matrix and requirments dependencies versions

### PR DESCRIPTION
**Pull request by auvipy**
lets see what breaks

### CODE REVIEW

**Comment by auvipy** [comment]
any idea to fix the failures?

**Comment by avelis** [comment]
@auvipy If you have time if you could update the readme doc to update the supported versions of Django that would be appreciated.

As for the unit test failures. One is a decimal precision issue. The other requires some effort to look into.

**Comment by auvipy** [comment]
I do have both time and interest to contribute on this project. I will try to fix and send pr. beside if you have any other lists of improvements you could create an issue and assign me to that too :)

**Comment by avelis** [comment]
@auvipy Any PR's are always welcome. I will do my best to review them in a timely fashion.

I can't assign this to you for some reason but if you want to look into this issue that would be great: https://github.com/django-silk/silk/issues/149

**Comment by auvipy** [comment]
ok i will dig into it

**Pull request merged**
