### PR TITLE
remove simplejson

### PR DESCRIPTION
**Pull request by digitaldavenyc**
First PR here, not sure on procedures so let me know if anything else is needed. Submitting this PR to remove simplejson from requirements and setup.py. It doesn't seem to be used anywhere in the code base anymore and actually caused a failure in the requests library on our project because requests defaults to simplejson if available.

### CODE REVIEW

**Comment by avelis** [comment]
@digitaldavenyc Thanks for your contribution.

**Comment by digitaldavenyc** [comment]
@avelis No problem, glad to help!

**Comment by avelis** [comment]
@digitaldavenyc In regards to procedures. I don't have anything official other than passing unit tests on TravisCI.

**Comment by digitaldavenyc** [comment]
Ok good to know. And it's ok to request the pull request from master?

**Comment by avelis** [comment]
@digitaldavenyc Absolutely!

I do my best to tackle issues when I have time. However, I encourage contributions as much as possible.

**Pull request merged**
