### PR TITLE
Render function instead of render_to_response

### PR DESCRIPTION
**Pull request by auvipy**
this is the preferred one

### CODE REVIEW

**Comment by avelis** [comment]
@auvipy After [reading the following stackoverflow question](http://stackoverflow.com/questions/5154358/django-what-is-the-difference-between-render-render-to-response-and-direc) I am ok with merging this in. If you could resolve the failing unit tests In this PR that would be greatly appreciated.

**Comment by auvipy** [comment]
I will try to fix the tests failing first then.

**Comment by avelis** [comment]
@auvipy I appreciate the effort. I also understand that there might be a failing test not associated to this change. I can be reasonable and expect that test to not get addressed in this PR.

**Comment by auvipy** [comment]
@avelis failed tests are a lot which take time to fix. so i would suggest to merge for now as is. i'm promising to comeback soon with more patches.

**Comment by avelis** [comment]
@auvipy I have merged in this commit.

**Pull request merged**
