### PR TITLE
versions upgrade and obsolete versions removal 

### PR DESCRIPTION
**Pull request by auvipy**

### CODE REVIEW

**Comment by avelis** [comment]
@auvipy Thanks for the effort. If you can take a look at the travis-ci.com build and resolve the build failures I can consider the PR for a merge.

**Comment by auvipy** [comment]
as I added 1.10a so some more tasks are needed to be resolved to pass 1.10a builds. but I can add allow failure of 1.10a on the matrix too. on the other side I refactored some url pattern related code which are removed in 1.10

**Comment by auvipy** [comment]
https://github.com/tomchristie/django-rest-framework/pull/4144 I can follow the work around and updating the patch

**Comment by avelis** [comment]
@auvipy thanks for adding in the allowed failures.

**Pull request merged**
